name: Windows portable

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    name: Build Windows portable distributions
    runs-on: windows-latest 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Create venv 
        run: python -m venv venv

      - name: Activate venv 
        run: .\venv\Scripts\activate
      
      - name: Install depenencies
        run: pip install ${{ github.workspace }}

      - name: Test...
        run: blrec --version