name: Windows portable

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    name: Build Windows portable distributions
    runs-on: windows-latest 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
        
      - name: Define variables 
        run: |
          echo "archive_name=blrec-${{ github.ref }}-win64.zip" >> $GITHUB_ENV
          echo "ffmpeg_archive=ffmpeg-n5.0-latest-win64-lgpl-shared-5.0.zip" >> $GITHUB_ENV
          echo "ffmpeg_archive_url=https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/${{ env.ffmpeg_archive }}" >> $GITHUB_ENV
          echo "python_version=3.10.4" >> $GITHUB_ENV
          echo "python_archive=python-${{ env.python_version }}-embed-amd64.zip" >> $GITHUB_ENV
          echo "python_archive_url=https://www.python.org/ftp/python/${{ env.python_version }}/${{ env.python_archive }}" >> $GITHUB_ENV

      - name: Download ffmpeg archive
        run: Invoke-WebRequest -Uri ${{ env.ffmpeg_archive_url }} -OutFile ${{ env.ffmpeg_archive }}

      - name: Download python archive
        run: Invoke-WebRequest -Uri ${{ env.python_archive_url }} -OutFile ${{ env.python_archive }}

      - name: Create build directory and dist directory
        run: New-Item -Path @("build", "dist") -ItemType Directory

      - name: Enter build directory
        run: Set-Location -Path "build"

      - name: Unzip ffmpeg archive
        run: Expand-Archive -LiteralPath "..\${{ env.ffmpeg_archive }}" -DestinationPath "."

      - name: Rename ffmpeg directory
        run: Rename-Item -Path ${{ env.ffmpeg_archive }}.Substring(0, ${{ env.ffmpeg_archive }}.Length - 4) "ffmpeg"

      - name: Sliming ffmpeg
        run: Get-ChildItem "ffmpeg" -Exclude @("LICENSE.txt", "bin") | Remove-Item -Recurse

      - name: Unzip Python archive
        run: Expand-Archive -LiteralPath "..\${{ env.python_archive }}" -DestinationPath "python"

      - name: Create venv 
        run: python -m venv venv

      - name: Activate venv 
        run: .\venv\Scripts\activate
      
      - name: Install packages
        run: pip install ${{ github.workspace }}

      - name: Copy site-packages
        run: robocopy venv\Lib\site-packages python\Lib\site-packages /mir /xd __pycache__* pip* setuptools*

      - name: Add search path
        run: Add-Content -Path "python\python310._pth" "Lib\site-packages"

      - name: Copy run.bat
        run: Copy-Item "${{ github.workspace }}\run.bat" -Destination ".\run.bat"

      - name: Remove venv
        run: Remove-Item -Path "venv" -Recurse -Force

      - name: Exit build directory
        run: Set-Location -Path ".."

      - name: Zip files
        run: Compress-Archive -Path "build\*" -DestinationPath "dist\${{ env.archive_name }}"
